#!  /bin/bash
#
#   Shell Script wrapper for a spoke length calculator.
#
#   Author: Matthew Signorini <matthew.signorini@gmail.com>

. ./classpath.sh

java mps.spoke.SpokeLength $1

# vim: ft=sh ts=4 sw=4 et
